name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push App image
      run: |
        docker build -t app ./app
        docker tag app:$IMAGE_TAG ${{ secrets.APP_ECR_URI }}:$IMAGE_TAG
        docker push ${{ secrets.APP_ECR_URI }}:$IMAGE_TAG

    - name: Build, tag, and push MySQL image
      run: |
        docker build -t mysql ./mysql
        docker tag mysql:$IMAGE_TAG ${{ secrets.MYSQL_ECR_URI }}:$IMAGE_TAG
        docker push ${{ secrets.MYSQL_ECR_URI }}:$IMAGE_TAG
